language: python
python: 3.5

sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

matrix:
  include:
  - env: TOX_ENV=py36-master
    python: 3.6
  - env: TOX_ENV=py36-2.0.x
    python: 3.6
  - env: TOX_ENV=py36-2.1.x
    python: 3.6
  - env: TOX_ENV=py36-2.2.x
    python: 3.6
  - env: TOX_ENV=py36-3.0.x
    python: 3.6
  - env: TOX_ENV=py37-master
    python: 3.7
  - env: TOX_ENV=py37-2.0.x
    python: 3.7
  - env: TOX_ENV=py37-2.1.x
    python: 3.7
  - env: TOX_ENV=py37-2.2.x
    python: 3.7
  - env: TOX_ENV=py37-3.0.x
    python: 3.7
  - env: TOX_ENV=py38-master
    python: 3.8
  - env: TOX_ENV=py38-2.0.x
    python: 3.8
  - env: TOX_ENV=py38-2.1.x
    python: 3.8
  - env: TOX_ENV=py38-2.2.x
    python: 3.8
  - env: TOX_ENV=py38-3.0.x
    python: 3.8
  allow_failures:
    - env: TOX_ENV=py35-master
    - env: TOX_ENV=py36-master
      python: 3.6
    - env: TOX_ENV=py37-master
      python: 3.7
    - env: TOX_ENV=py38-master
      python: 3.8
  fast_finish: true

install:
  - pip install tox coveralls --cache-dir $HOME/.pip-cache

script:
  - tox -e $TOX_ENV

after_success:
  coveralls
